# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
name: Android CI/CD
on:
  push:
    branches:
- main # Change this to your main branch name
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
steps:
- name: Checkout code
  uses: actions/checkout@v2

- name: Set up JDK 11
  uses: actions/setup-java@v2
  with:
    distribution: 'adopt'
    java-version: '11'
- name: Build and test
  run: |
    chmod +x gradlew
    ./gradlew assembleRelease
    ./gradlew test
- name: Upload APK
  uses: actions/upload-artifact@v2
  with:
    name: app-release
    path: app/build/outputs/apk/release/app-release.apk

